# Copyright (c) 2025 知识库管理系统. All rights reserved.

"""
Django settings for jj_system project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import datetime
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'rest_framework',
    'rest_framework_simplejwt',
    'user.apps.UserConfig',#用户模块
    'role.apps.RoleConfig',#角色模块
    'menu.apps.MenuConfig',#菜单模块
    'post.apps.PostConfig',#岗位模块
    'level.apps.LevelConfig',#职级模块
    'department.apps.DepartmentConfig',#部门模块
    'log.apps.LogConfig',#日志模块
    'blacklist.apps.BlacklistConfig',#黑名单模块
    'manhour.apps.ManhourConfig',#工时模块
    'items.apps.ItemsConfig',#项目编号
    'repository.apps.RepositoryConfig',#知识库模块
    'classify.apps.ClassifyConfig',#分类模块
    'event.apps.EventConfig',#事件管理模块
    'file_manager.apps.FileManagerConfig',#文件管理模块
    'approval.apps.ApprovalConfig',#审批流程模块
    'notification.apps.NotificationConfig',#消息通知模块


]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.JwtAuthenticationMiddleware',
    'log.middleware.OperLogMiddleware',


]

#设置访问白名单
CORS_ORIGIN_ALLOW_ALL = True
#设置允许携带cookie
CORS_ALLOW_CREDENTIALS = True
#设置默认允许请求头方法
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
]
#允许所有请求头
CORS_ALLOW_HEADERS = ['*']
# 禁用 CSRF 验证（因为使用 JWT）
CSRF_TRUSTED_ORIGINS = [
    # 'http://192.168.111.77:8080',
    # 'http://localhost:8080',
    # 'http://127.0.0.1:8080',
    # 'http://xxx:8080',      # 前端地址
    # 'http://xxx:8000'  # 后端地址
]

ROOT_URLCONF = 'jj_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jj_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'xxx',  # 数据库名
        'USER': 'xxx',
        'PASSWORD': 'xxx',
        'HOST': 'xxx',
        'PORT': '3306',
        # 为数据库连接指定时区
        'TIME_ZONE': 'Asia/Shanghai',
    }
}


# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'repository': {  # 为repository应用设置日志
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True # 保持为True以支持时区

# # 添加以下配置以确保正确处理时区
# USE_L10N = True  # 启用本地化格式
# 添加日期时间格式化配置
DATE_FORMAT = 'Y-m-d'
DATETIME_FORMAT = 'Y-m-d H:i:s'
SHORT_DATE_FORMAT = 'Y-m-d'
SHORT_DATETIME_FORMAT = 'Y-m-d H:i:s'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# 生产环境媒体文件域名（生产环境配置）
MEDIA_DOMAIN = 'http://xxx:8080'


# 2. 配置 DRF 认证
# 注意：我们使用自定义中间件进行认证，所以完全禁用 DRF 的默认认证和权限类
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],  # 完全禁用 DRF 认证
    'DEFAULT_PERMISSION_CLASSES': [],  # 完全禁用 DRF 默认权限
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),  # 访问令牌有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),     # 刷新令牌有效期
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

