# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysBlackList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_comment="企业名称", max_length=100, verbose_name="企业名称"
                    ),
                ),
                (
                    "contract_time",
                    models.DateField(
                        blank=True,
                        db_comment="合同履约日期",
                        null=True,
                        verbose_name="合同履约日期",
                    ),
                ),
                (
                    "deadline_time",
                    models.DateField(
                        blank=True, db_comment="逾期日期", null=True, verbose_name="逾期日期"
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        blank=True,
                        db_comment="类型",
                        max_length=100,
                        null=True,
                        verbose_name="类型",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True, db_comment="状态", null=True, verbose_name="状态"
                    ),
                ),
                (
                    "amount_type",
                    models.IntegerField(
                        blank=True,
                        db_comment="金额类型 1、合同金额 2、订单金额",
                        null=True,
                        verbose_name="金额类型 1、合同金额 2、订单金额",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        blank=True, db_comment="金额", null=True, verbose_name="金额"
                    ),
                ),
                (
                    "archival_information",
                    models.CharField(
                        blank=True,
                        db_comment="备案信息 0、未备案 1、已备案",
                        max_length=100,
                        null=True,
                        verbose_name="备案信息 0、未备案 1、已备案",
                    ),
                ),
                (
                    "actual_time",
                    models.DateField(
                        blank=True, db_comment="实际日期", null=True, verbose_name="实际日期"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="分类",
                        max_length=500,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
            ],
            options={
                "verbose_name": "各种名单表",
                "verbose_name_plural": "各种名单表",
                "db_table": "sys_BlackList",
            },
        ),
    ]
