# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="用户ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="用户名", max_length=150, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_comment="密码", max_length=255, null=True, verbose_name="密码"
                    ),
                ),
                (
                    "realname",
                    models.CharField(
                        db_comment="用户姓名", max_length=150, verbose_name="用户姓名"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        db_comment="用户花名", max_length=150, verbose_name="用户花名"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "男"), (2, "女"), (3, "保密")],
                        db_comment="性别：1-男 2-女 3-保密",
                        default=1,
                        verbose_name="性别：1-男 2-女 3-保密",
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        db_comment="用户头像", max_length=255, verbose_name="用户头像"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_comment="手机号", max_length=30, verbose_name="手机号"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        db_comment="用户邮箱", max_length=50, verbose_name="用户邮箱"
                    ),
                ),
                ("birthday", models.DateField(db_comment="出生日期", verbose_name="出生日期")),
                (
                    "dept_id",
                    models.IntegerField(
                        db_comment="部门ID", default=0, verbose_name="部门ID"
                    ),
                ),
                (
                    "level_id",
                    models.IntegerField(
                        db_comment="职级ID", default=0, verbose_name="职级ID"
                    ),
                ),
                (
                    "position_id",
                    models.IntegerField(
                        db_comment="岗位ID", default=0, verbose_name="岗位ID"
                    ),
                ),
                (
                    "province_code",
                    models.CharField(
                        db_comment="省份编码", max_length=30, verbose_name="省份编码"
                    ),
                ),
                (
                    "city_code",
                    models.CharField(
                        db_comment="城市编码", max_length=30, verbose_name="城市编码"
                    ),
                ),
                (
                    "district_code",
                    models.CharField(
                        db_comment="县区编码", max_length=30, verbose_name="县区编码"
                    ),
                ),
                (
                    "address_info",
                    models.CharField(
                        db_comment="省市区信息", max_length=255, verbose_name="省市区信息"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_comment="详细地址", max_length=255, verbose_name="详细地址"
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        db_comment="个人简介", max_length=255, verbose_name="个人简介"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (2, "禁用")],
                        db_comment="状态：1-正常 2-禁用",
                        default=1,
                        verbose_name="状态：1-正常 2-禁用",
                    ),
                ),
                (
                    "login_date",
                    models.DateTimeField(
                        auto_now=True, db_comment="最后登录时间", verbose_name="最后登录时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_comment="备注", max_length=500, verbose_name="备注"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(db_comment="排序", default=0, verbose_name="排序"),
                ),
                (
                    "can_view_commenter",
                    models.IntegerField(
                        choices=[(0, "否"), (1, "是")],
                        db_comment="是否可以查看评论人信息",
                        default=0,
                        verbose_name="是否可以查看评论人信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
                "db_table": "sys_user",
            },
        ),
    ]
