# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysManhour",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dept_id",
                    models.CharField(
                        db_comment="部门id", max_length=100, verbose_name="部门id"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_comment="用户id", max_length=100, verbose_name="用户id"
                    ),
                ),
                ("date_time", models.DateField(db_comment="时间", verbose_name="时间")),
                (
                    "report_type",
                    models.CharField(
                        db_comment="类型", max_length=100, verbose_name="类型"
                    ),
                ),
                (
                    "project_number",
                    models.CharField(
                        db_comment="项目编号及名称", max_length=100, verbose_name="项目编号及名称"
                    ),
                ),
                (
                    "job_description",
                    models.TextField(db_comment="工作描述", verbose_name="工作描述"),
                ),
                ("man_hour", models.IntegerField(db_comment="工时", verbose_name="工时")),
                (
                    "issue",
                    models.CharField(
                        db_comment="存在的问题", max_length=100, verbose_name="存在的问题"
                    ),
                ),
                (
                    "coordinate",
                    models.CharField(
                        db_comment="需协调的事项", max_length=100, verbose_name="需协调的事项"
                    ),
                ),
                (
                    "work_plan",
                    models.CharField(
                        db_comment="次日工作计划", max_length=500, verbose_name="次日工作计划"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_comment="备注", max_length=500, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "db_table": "sys_manhour",
            },
        ),
    ]
