# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "project_number",
                    models.CharField(
                        db_comment="项目编号及名称", max_length=100, verbose_name="项目编号及名称"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_comment="用户ID", default=0, verbose_name="用户ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "db_table": "sys_item",
            },
        ),
    ]
