# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysNotification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.IntegerField(db_comment="接收用户ID", verbose_name="接收用户ID"),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="消息标题", max_length=255, verbose_name="消息标题"
                    ),
                ),
                ("content", models.TextField(db_comment="消息内容", verbose_name="消息内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("event", "事件通知"),
                            ("system", "系统通知"),
                            ("approval", "审批通知"),
                        ],
                        db_comment="消息类型",
                        default="system",
                        max_length=50,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "未读"), (1, "已读")],
                        db_comment="消息状态：0-未读 1-已读",
                        default=0,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "related_id",
                    models.IntegerField(
                        blank=True, db_comment="关联的业务ID", null=True, verbose_name="关联ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        blank=True, db_comment="阅读时间", null=True, verbose_name="阅读时间"
                    ),
                ),
            ],
            options={
                "db_table": "sys_notification",
                "ordering": ["-create_time"],
            },
        ),
    ]
