# Generated by Django 5.2.6 on 2026-06-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileManager",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小")),
                ("file_type", models.CharField(max_length=100, verbose_name="文件类型")),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("已上传", "已上传"), ("处理中", "处理中"), ("已删除", "已删除")],
                        default="已上传",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件管理",
                "verbose_name_plural": "文件管理",
                "db_table": "sys_file_manager",
                "ordering": ["-upload_time"],
            },
        ),
    ]
