# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="岗位ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="岗位ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="岗位名称", max_length=150, verbose_name="岗位名称"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_comment="岗位顺序", default=0, verbose_name="岗位顺序"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (2, "停用")],
                        db_comment="岗位状态：1-正常 2-停用",
                        default=1,
                        verbose_name="岗位状态：1-正常 2-停用",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "岗位表",
                "verbose_name_plural": "岗位表",
                "db_table": "sys_post",
            },
        ),
    ]
