# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassifyItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dept_id",
                    models.IntegerField(
                        db_comment="部门id", default=0, verbose_name="部门id"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_comment="用户名id", default=0, verbose_name="用户名id"
                    ),
                ),
                (
                    "types",
                    models.IntegerField(
                        db_comment="分类id ：0-类型，1-分类",
                        default=0,
                        verbose_name="分类id ：0-未分类，1-分类",
                    ),
                ),
                (
                    "project_number",
                    models.CharField(
                        db_comment="分类名称", max_length=100, verbose_name="分类名称"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "db_table": "sys_Classify_item",
            },
        ),
    ]
