# Generated by Django 5.2.6 on 2026-06-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dept_id",
                    models.CharField(
                        db_comment="部门id", max_length=100, verbose_name="部门id"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_comment="用户id", max_length=100, verbose_name="用户id"
                    ),
                ),
                (
                    "event_number",
                    models.CharField(
                        db_comment="事件编号",
                        max_length=250,
                        null=True,
                        verbose_name="事件编号",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_comment="事件名称",
                        max_length=250,
                        null=True,
                        verbose_name="事件名称",
                    ),
                ),
                (
                    "principal",
                    models.CharField(
                        db_comment="负责人", max_length=250, null=True, verbose_name="负责人"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (2, "停用")],
                        db_comment="事件状态：1-正常 2-停用",
                        default=1,
                        verbose_name="事件状态：1-正常 2-停用",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        db_comment="项目起始时间",
                        null=True,
                        verbose_name="项目起始时间",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_comment="项目终止时间",
                        null=True,
                        verbose_name="项目终止时间",
                    ),
                ),
                (
                    "notification_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="配置通知时间，格式：YYYY-MM-DD HH:MM:SS，用于监控什么时间段去发送消息通知",
                        null=True,
                        verbose_name="配置通知时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_comment="备注", max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "db_table": "sys_event",
            },
        ),
        migrations.CreateModel(
            name="SysEventAssignmentHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.IntegerField(
                        choices=[(1, "分配"), (2, "取消分配")], verbose_name="操作类型"
                    ),
                ),
                (
                    "operate_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.sysevent",
                        verbose_name="关联事件",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_operator",
                        to="user.sysuser",
                        verbose_name="操作人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_user",
                        to="user.sysuser",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "db_table": "sys_event_assignment_history",
                "ordering": ["-operate_time"],
            },
        ),
        migrations.CreateModel(
            name="SysEventRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="event.sysevent"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.sysuser"
                    ),
                ),
            ],
            options={
                "db_table": "sys_event_role",
            },
        ),
    ]
