# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysApproval",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "approval_type",
                    models.IntegerField(
                        choices=[(1, "删除用户"), (2, "删除角色"), (3, "数据导出")],
                        db_comment="审批类型：1-删除用户 2-删除角色 3-数据导出",
                        verbose_name="审批类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="审批标题", max_length=200, verbose_name="审批标题"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        db_comment="审批内容详情", null=True, verbose_name="审批内容"
                    ),
                ),
                (
                    "target_id",
                    models.IntegerField(
                        db_comment="被操作对象的ID（如用户ID）", null=True, verbose_name="目标ID"
                    ),
                ),
                (
                    "target_data",
                    models.TextField(
                        db_comment="被操作对象的数据快照（JSON格式）", null=True, verbose_name="目标数据"
                    ),
                ),
                (
                    "applicant_id",
                    models.IntegerField(db_comment="提交审批的用户ID", verbose_name="申请人ID"),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        db_comment="提交审批的用户姓名", max_length=50, verbose_name="申请人姓名"
                    ),
                ),
                (
                    "approver_id",
                    models.IntegerField(
                        db_comment="审批人的用户ID", null=True, verbose_name="审批人ID"
                    ),
                ),
                (
                    "approver_name",
                    models.CharField(
                        db_comment="审批人姓名",
                        max_length=50,
                        null=True,
                        verbose_name="审批人姓名",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待审批"), (2, "已通过"), (3, "已拒绝"), (4, "已撤销")],
                        db_comment="审批状态：1-待审批 2-已通过 3-已拒绝 4-已撤销",
                        default=1,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approve_remark",
                    models.TextField(
                        db_comment="审批人的审批意见", null=True, verbose_name="审批意见"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="审批提交时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "approve_time",
                    models.DateTimeField(
                        db_comment="审批处理时间", null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_comment="备注", max_length=500, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
                "db_table": "sys_approval",
            },
        ),
    ]
