# Generated by Django 5.2.6 on 2026-06-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysRepository",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dept_id",
                    models.IntegerField(
                        db_comment="部门id", default=0, verbose_name="部门id"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_comment="用户名id", default=0, verbose_name="用户名id"
                    ),
                ),
                (
                    "event_id",
                    models.IntegerField(
                        db_comment="事件id", default=0, verbose_name="事件id"
                    ),
                ),
                (
                    "event_occur_time",
                    models.DateField(db_comment="事件发生时间", verbose_name="事件发生时间"),
                ),
                (
                    "address",
                    models.CharField(
                        db_comment="发生地点", max_length=250, verbose_name="发生地点"
                    ),
                ),
                (
                    "is_temp",
                    models.BooleanField(
                        db_comment="临时保存标识", default=False, verbose_name="是否临时保存"
                    ),
                ),
                (
                    "temp_version",
                    models.IntegerField(
                        db_comment="临时保存版本计数", default=0, verbose_name="临时版本号"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        db_comment="确认状态标识", default=False, verbose_name="是否已确认"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("confirmed", "已确认"),
                        ],
                        db_comment="控制编辑权限的状态",
                        default="draft",
                        max_length=20,
                        verbose_name="记录状态",
                    ),
                ),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "仅自己"), (2, "部门"), (3, "全员")],
                        db_comment="控制记录可见范围：1-仅自己，2-部门，3-全员",
                        default=3,
                        verbose_name="可见性",
                    ),
                ),
                (
                    "types",
                    models.IntegerField(db_comment="类型", default=0, verbose_name="类型"),
                ),
                (
                    "classify",
                    models.IntegerField(db_comment="分类", default=0, verbose_name="分类"),
                ),
                ("title", models.TextField(db_comment="标题", verbose_name="标题")),
                ("content", models.TextField(db_comment="内容", verbose_name="内容")),
                (
                    "upvote",
                    models.IntegerField(
                        db_comment="点赞数", default=0, verbose_name="点赞数"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_comment="备注", max_length=500, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库",
                "verbose_name_plural": "知识库",
                "db_table": "sys_repository",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryReview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "review_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="复盘日期"),
                ),
                (
                    "what_happened",
                    models.TextField(help_text="描述事件的实际发生情况", verbose_name="发生了什么"),
                ),
                (
                    "what_went_well",
                    models.TextField(help_text="列出成功和积极的方面", verbose_name="做得好的地方"),
                ),
                (
                    "what_not_went_well",
                    models.TextField(help_text="识别问题和挑战", verbose_name="需要改进的地方"),
                ),
                (
                    "lessons_learned",
                    models.TextField(help_text="从事件中获得的关键经验教训", verbose_name="学到的经验"),
                ),
                (
                    "action_items",
                    models.TextField(help_text="未来如何改进的具体措施", verbose_name="行动计划"),
                ),
                (
                    "effectiveness_score",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        verbose_name="有效性评分",
                    ),
                ),
                (
                    "improvement_potential",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        verbose_name="改进潜力评分",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="复盘人",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="repository.sysrepository",
                        verbose_name="知识库条目",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库复盘",
                "verbose_name_plural": "知识库复盘",
                "db_table": "sys_repository_review",
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_url",
                    models.CharField(
                        db_comment="图片的完整URL地址", max_length=500, verbose_name="图片URL"
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        db_comment="图片在服务器上的相对路径", max_length=500, verbose_name="图片路径"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        db_comment="图片文件大小（字节）", default=0, verbose_name="文件大小"
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="图片上传时间", verbose_name="上传时间"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="repository.sysrepository",
                        verbose_name="知识库条目",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库图片",
                "verbose_name_plural": "知识库图片",
                "db_table": "sys_repository_image",
                "ordering": ["-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dept_id",
                    models.IntegerField(
                        db_comment="部门id", default=0, verbose_name="部门id"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_comment="用户名id", default=0, verbose_name="用户名id"
                    ),
                ),
                (
                    "event_id",
                    models.IntegerField(
                        db_comment="事件id", default=0, verbose_name="事件id"
                    ),
                ),
                (
                    "event_occur_time",
                    models.DateField(db_comment="事件发生时间", verbose_name="事件发生时间"),
                ),
                (
                    "address",
                    models.CharField(
                        db_comment="发生地点", max_length=250, verbose_name="发生地点"
                    ),
                ),
                (
                    "types",
                    models.IntegerField(db_comment="类型", default=0, verbose_name="类型"),
                ),
                (
                    "classify",
                    models.IntegerField(db_comment="分类", default=0, verbose_name="分类"),
                ),
                ("title", models.TextField(db_comment="标题", verbose_name="标题")),
                ("content", models.TextField(db_comment="内容", verbose_name="内容")),
                (
                    "upvote",
                    models.IntegerField(
                        db_comment="点赞数", default=0, verbose_name="点赞数"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(db_comment="修改版本号", verbose_name="版本号"),
                ),
                (
                    "modified_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="修改时间", verbose_name="修改时间"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        db_comment="备注", max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.sysrepository",
                        verbose_name="知识库条目",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库历史记录",
                "verbose_name_plural": "知识库历史记录",
                "db_table": "sys_repository_history",
                "ordering": ["-modified_time"],
            },
        ),
        migrations.CreateModel(
            name="SysRepositoryComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reply_to_user_id",
                    models.IntegerField(
                        blank=True,
                        db_comment="被回复人用户ID",
                        null=True,
                        verbose_name="被回复人ID",
                    ),
                ),
                ("content", models.TextField(db_comment="评论内容", verbose_name="评论内容")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="评论时间", verbose_name="评论时间"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="repository.sysrepositorycomment",
                        verbose_name="父评论",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="repository.sysrepository",
                        verbose_name="知识库条目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库评论",
                "verbose_name_plural": "知识库评论",
                "db_table": "sys_repository_comment",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryLike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.IntegerField(db_comment="点赞用户ID", verbose_name="用户ID"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="点赞时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.sysrepository",
                        verbose_name="知识库条目",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库点赞",
                "verbose_name_plural": "知识库点赞",
                "db_table": "sys_repository_like",
                "unique_together": {("repository", "user_id")},
            },
        ),
    ]
