# Generated by Django 5.2.6 on 2026-06-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_comment="角色名称", max_length=30, null=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="角色权限字符串",
                        max_length=100,
                        null=True,
                        verbose_name="角色权限字符串",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (2, "停用")],
                        db_comment="角色状态：1-正常 2-停用",
                        default=1,
                        verbose_name="角色状态：1-正常 2-停用",
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_comment="角色排序", default=0, verbose_name="角色排序"
                    ),
                ),
                (
                    "data_scope",
                    models.IntegerField(
                        choices=[(1, "全部数据"), (2, "本部门及下级部门"), (3, "仅本部门"), (4, "仅本人")],
                        db_comment="数据权限范围：1-全部数据 2-本部门及下级部门 3-仅本部门 4-仅本人",
                        default=4,
                        verbose_name="数据权限范围",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_comment="备注", max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "db_table": "sys_role",
            },
        ),
        migrations.CreateModel(
            name="SysUserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="role.sysrole"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.sysuser"
                    ),
                ),
            ],
            options={
                "db_table": "sys_user_role",
            },
        ),
    ]
