# Generated by Django 5.2.6 on 2026-06-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysOperLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "operation",
                    models.CharField(
                        db_comment="操作内容", max_length=200, verbose_name="操作内容"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        db_comment="请求方法", max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_comment="请求路径", max_length=255, verbose_name="请求路径"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        db_comment="客户端IP", max_length=50, verbose_name="客户端IP"
                    ),
                ),
                (
                    "params",
                    models.TextField(db_comment="请求参数", null=True, verbose_name="请求参数"),
                ),
                (
                    "status",
                    models.IntegerField(
                        db_comment="操作状态(0成功1失败)",
                        default=0,
                        verbose_name="操作状态(0成功1失败)",
                    ),
                ),
                (
                    "error_msg",
                    models.TextField(db_comment="错误信息", null=True, verbose_name="错误信息"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="操作用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.sysuser",
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "sys_oper_log",
            },
        ),
    ]
