# Generated by Django 5.2.6 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysDept",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="部门ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="部门ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="部门名称", max_length=150, verbose_name="部门名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="部门编码", max_length=150, verbose_name="部门编码"
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        default=0,
                        help_text="部门类型：1-公司 2-子公司 3-部门 4-小组",
                        verbose_name="部门类型：1-公司 2-子公司 3-部门 4-小组",
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(
                        db_comment="上级部门ID", default=0, verbose_name="上级部门ID"
                    ),
                ),
                (
                    "leader",
                    models.CharField(
                        blank=True,
                        db_comment="部门负责人",
                        max_length=150,
                        null=True,
                        verbose_name="部门负责人",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_comment="备注", max_length=500, verbose_name="备注"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(db_comment="排序", default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "部门表",
                "verbose_name_plural": "部门表",
                "db_table": "sys_Dept",
            },
        ),
    ]
